version: "3.9"

services:
  tutorial_postgres:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    command: postgres -c wal_level=logical
    volumes:
      # automatically runs drizzle migrations in alphabetical order
      - ./migrations:/docker-entrypoint-initdb.d
